"""empty message

Revision ID: 1bef7da3bd9f
Revises: 7324e80d462b
Create Date: 2020-05-26 17:54:42.474037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bef7da3bd9f'
down_revision = '7324e80d462b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'cash',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'cash',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
