"""empty message

Revision ID: 3c6c57b11294
Revises: a556e2cc8a17
Create Date: 2020-05-26 16:07:48.158503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6c57b11294'
down_revision = 'a556e2cc8a17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_history', 'cost',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('transaction_history', 'date_time',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('transaction_history', 'price',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('transaction_history', 'shares',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_history', 'shares',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transaction_history', 'price',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('transaction_history', 'date_time',
               existing_type=sa.DATETIME(),
               nullable=False)
    op.alter_column('transaction_history', 'cost',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
