"""empty message

Revision ID: c9a8330c9091
Revises: b344df5d1c3e
Create Date: 2020-05-26 16:24:14.885771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a8330c9091'
down_revision = 'b344df5d1c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transations',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('symbol', sa.String(length=20), nullable=True),
                    sa.Column('shares', sa.Integer(), nullable=True),
                    sa.Column('price', sa.Float(), nullable=True),
                    sa.Column('cost', sa.Float(), nullable=True),
                    sa.Column('date_time', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('transaction_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_history',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('user_id', sa.INTEGER(), nullable=True),
                    sa.Column('symbol', sa.VARCHAR(length=20), nullable=True),
                    sa.Column('shares', sa.INTEGER(), nullable=True),
                    sa.Column('price', sa.FLOAT(), nullable=True),
                    sa.Column('cost', sa.FLOAT(), nullable=True),
                    sa.Column('date_time', sa.DATETIME(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('transations')
    # ### end Alembic commands ###
